export const getHeroSummary = (heroPath: string) =>
  ({
    antimage: {
      title: 'CORTA OS SEUS INIMIGOS COM ATAQUES QUE DRENAM MANA',
      history:
        'Os monges de Turstarkuri observavam os vales escarpados abaixo do seu monastério na montanha, enquanto hordas após hordas de invasores passavam pelos reinos inferiores. Ascéticos e pragmáticos, mantinham-se indiferentes a conflitos mundanos no seu remoto ninho monástico, envoltos em uma meditação que não conhecia deuses ou elementos de magia. Então veio a Legião do Deus Morto, cruzados com o sinistro mandato de substituir todo culto local pela niilosofia venenosa do seu Senhor Sem-vida. De uma paisagem que não conheceu nada além de sangue e batalha por mil anos, eles arrancaram as almas e ossos de incontáveis legiões caídas e os lançaram contra Turstarkuri. O monastério mal conseguiu resistir ao ataque por uma quinzena, e os poucos monges que se deram ao trabalho de sair da sua meditação acreditavam que os invasores eram apenas visões demoníacas enviadas para distraí-los das suas contemplações. Eles morreram sentados nas suas almofadas de seda. Apenas um jovem sobreviveu – um peregrino que foi recebido como um acólito, buscando sabedoria, mas que ainda estava para ser admitido no monastério. Ele assistiu com horror enquanto os monges a quem tinha servido chá e urtigas eram massacrados e então reerguidos para se juntar às hostes sacerdotais do Deus Morto. Com pouco mais que alguns estimados pergaminhos dogmáticos dos Turstarkuri, ele escapou sem ser visto para a relativa segurança de outras terras, jurando não somente obliterar os usuários de magia do Deus Morto – mas pôr um fim à magia como um todo Fechar história Caso o Anti-Mage tenha a oportunidade de reunir toda a sua força, poucos podem frear as suas investidas. Drenando o mana dos seus inimigos a cada ataque ou se teletransportando por pequenas distâncias para fugir de uma emboscada, encurralá-lo é um desafio para qualquer inimigo.',
      shortDescription:
        'Caso o Anti-Mage tenha a oportunidade de reunir toda a sua força, poucos podem frear as suas investidas. Drenando o mana dos seus inimigos a cada ataque ou se teletransportando por pequenas distâncias para fugir de uma emboscada, encurralá-lo é um desafio para qualquer inimigo.',
    },
    axe: {
      title: 'PROVOCA E FORÇA INIMIGOS A ATACÁ-LO',
      history:
        'Mesmo quando soldado de baixa patente do Exército da Névoa Vermelha, Mogul Khan ambicionava a patente de General da Névoa Vermelha. Batalha após batalha, ele provou o seu valor através dos seus atos violentos. A sua ascensão pelas patentes foi ajudada pelo fato dele nunca hesitar em decapitar um superior. Durante os sete anos da Campanha dos Mil Lagos, destacou-se dos outros em gloriosos massacres, a sua estrela da fama brilhando cada vez mais enquanto o número de companheiros de armas minguava constantemente. Na noite da vitória suprema, o Axe declarou-se o novo General da Névoa Vermelha e tomou o título máximo de "Axe". Mas os números das suas tropas haviam chegado a zero. Claro, muitos morreram em batalha, mas um número significativo também caíra pela lâmina de Axe. Desnecessário dizer, agora a maioria dos soldados evita a sua liderança. Mas isso é insignificante para Axe, que sabe que um exército de um homem só é, sem dúvida, o melhor.',
      shortDescription:
        'Um após o outro, o Axe corta os seus inimigos. Marchando à frente da sua equipe, ele prende os inimigos em uma batalha e então revida os seus golpes com um giro mortal da sua arma. Passando a sua lâmina de abate através de um inimigo enfraquecido, ele está sempre avançando.',
    },
    bane: {
      title: 'PUTS HIS ENEMIES TO SLEEP, INCAPACITATING THEM',
      history:
        'Quando os deuses têm pesadelos, é o Bane Elemental que os traz. Também conhecido como Atropos, Bane nasceu a partir dos terrores da meia-noite da deusa Nyctasha. Sendo uma força de terror poderosa demais para ser contida em sonhos, ele veio ao mundo através dos seus torpores, alimentou-se da sua imortalidade e tomou a sua forma nebulosa do sangue escuro dela. Ele é a essência do medo. Mortais que ouvem a sua voz escutam os seus segredos mais sombrios sussurrados nos seus ouvidos. Ele chama pelo medo oculto no coração de cada herói. Ficar acordado não traz proteção, pois o sangue negro e sempre gotejante de Bane é um piche que prende os seus inimigos em pesadelos. Na presença de Bane, nenhum herói se esquece de temer o escuro.',
      shortDescription:
        'O Bane aterroriza os seus adversários com o seu arsenal de habilidades desativadoras. Seja aprisionando um inimigo dentro de um pesadelo contagioso ou o imobilizando, ele dá aos seus aliados todo o tempo necessário para abater os seus adversários.',
    },
    bloodseeker: {
      title: 'GANHA VELOCIDADE AO PERSEGUIR INIMIGOS COM POUCA VIDA',
      history:
        'Strygwyr, o Bloodseeker, é um caçador autorizado por ritual, o Cão de Caça dos Gêmeos Esfolados, enviado dos picos enevoados de Xhacatocatl em busca de sangue. Os Esfolados requerem quantidades oceânicas de sangue para se manterem saciados e apaziguados, e em breve sugariam a sua população do seu império montanhoso se os sacerdotes dos elevados planaltos não os satisfizessem. Strygwyr, portanto, vai à procura de carnificina. A energia vital de qualquer sangue que ele derrama flui imediatamente para os Gêmeos através das marcas sagradas nas suas armas e armadura. Ao longo dos anos, ele passou a encorporar a energia de uma fera perversa; em batalha ele é selvagem como um chacal. Por trás da Máscara do Bloodseeker, na afobação de saciamento de sangue, diz-se que por vezes se pode ver os traços dos Esfolados tomando posse direta do seu Cão de Caça.',
      shortDescription:
        'O Bloodseeker força os seus inimigos a tomarem difíceis decisões. Capaz de forçá-los a recuar banhando uma grande área com um ritual danoso, a sua terrível habilidade Ultimate exige que os seus adversários fiquem parados ou morram andando.',
    },
    crystal_maiden: {
      title: 'UNLEASHES A HIGH DAMAGE BLIZZARD UPON HER FOES',
      history:
        'Nascida em uma região de clima temperado e criada com a sua escaldante irmã mais velha Lina, Rylai, conhecida como a Crystal Maiden, rapidamente descobriu que a sua inata afinidade elementar para o gelo criava problemas para todos à sua volta. Nascentes e rios de montanha congelavam em momentos se ela parava ao pé deles para descansar; colheitas que estavam amadurecendo eram atingidas pela geada e pomares cheios de frutos transformavam-se em labirintos de gelo e acabavam por se arruinar, estragados. Quando os seus pais exasperados enviaram Lina para o equador, Rylai encontrou-se exilada na região fria e nortenha de Geleiras Devastadas, onde foi abrigada por um Feiticeiro do Gelo que tinha esculpido para si próprio um eremitério no ponto mais alto da Geleira Coração Azul. Após um longo período de estudo, o feiticeiro declarou que ela estava pronta para praticar sozinha e deixou-a tomar o seu lugar, descendo à geleira para hibernar durante mil anos. O seu controle das Artes do Gelo apenas tem aumentado desde então, e agora as suas habilidades são inigualáveis.',
      shortDescription:
        'Capaz de suprir aliados com mana e retardar inimigos para garantir um abate, a Crystal Maiden pode ser uma adição bem-vinda a qualquer equipe. E, quando a oportunidade surgir, ela pode desencadear uma massiva habilidade Ultimate para devastar os seus adversários.',
    },
    drow_ranger: {
      title: 'CAUSA RETARDO COM AS SUAS FLECHAS DE GELO',
      history: '',
      shortDescription:
        'Poucos podem escapar da Drow Ranger quando estão no seu alcance. Após silenciar os seus inimigos com uma rajada arrepiante, ela acaba com eles com uma chuva de flechas gélidas e retardantes às quais poucos conseguem sobreviver.',
    },
    dark_seer: {
      title: 'PULLS AND MANIPULATES HIS ENEMIES POSITIONS',
      history: '',
      shortDescription:
        'Versátil e estratégico, o Dark Seer sabe como perfeitamente manipular o posicionamento dos seus inimigos. Com as suas habilidades de sucção, ele pode tanto agrupá-los para que os seus aliados possam atacá-los quanto voltá-los contra eles mesmos, empurrando-os para a sua parede replicante.',
    },
    dark_willow: {
      title: 'HAS AN ARSENAL OF DISABLES AT HER DISPOSAL',
      history:
        'Crianças adoram contar histórias sobre aventuras fantásticas de fadas... Isso porque as crianças não sabem que a maioria das fadas são seres idiotas e rancorosos. E no mundo das fadas rancorosas há poucos nomes mais desprezados do que Mireska Sunbreeze.\n\nFilha de um rei comerciante, Mireska cresceu em Revtel; uma nação sem lei onde manipulação e assassinato eram a norma. Porém, embora ela fosse adepta de seguir a etiqueta, tradições e rituais sociais que permeavam cada momento da sua vida, ela acabou cansando de tudo aquilo.\n\nEntão, Mireska fez o que a maioria das crianças rebeldes fazem: queimou toda a propriedade da sua família e partiu com o seu espírito de estimação Jex para levar uma vida errante.',
      shortDescription:
        'Uma pequena agitação nas sombras pode ser tudo o que os inimigos da Dark Willow veem, enquanto ela engana a visão e controla o movimento dos seus inimigos com os seus astutos truques de fada. Invocando poderes muito mais ancestrais do que qualquer magia conhecida, ela aprisiona inimigos antes de libertar sobre eles toda a ira e terror do reino feérico.',
    },
    dawnbreaker: {
      title: 'SALTA PARA AJUDAR OS SEUS ALIADOS, ONDE QUER QUE ESTEJAM',
      history:
        'Durante éons após o início da era da luz com o êxodo do Guardião, alguns dentre os primeiros na linhagem solar começaram a se unir contra o caos decorrente do desaparecimento do seu criador ancestral. Autointitulados Filhos da Luz, eles não viam ninguém digno de ocupar o posto deixado pelo Guardião; eles ansiavam por acabar com os ataques da escuridão, criando exércitos gloriosos para expurgar o cosmos de todas as criaturas da noite primordial.\n\nValora, a Dawnbreaker, a mais honrada guerreira entre os Filhos, é o arauto brilhante da grandiosidade da ordem e luz. Forjada a partir do coração de uma jovem estrela metálica e despertada com um sopro dourado para a sua nova vida, Valora foi convocada para espalhar o brilho da sabedoria dos Filhos por entre as maiores escuridões do universo — incendiando os céus com cada balanço do seu martelo celestial em meio às infindáveis batalhas para controlar os avanços do caos.\n\nCom o tempo, os Filhos também revelaram outro propósito para a Dawnbreaker. Eles descobriram uma forma de permear a sua luz interior por todo o cosmos — destruindo a escuridão na sua totalidade, para sempre. Valora foi enviada como fonte de um grande poder, a peça final naquele grande plano. Porém, pela primeira vez, Valora e o seu martelo fracassaram... E o preço foi alto. A faísca dos Filhos da Luz fora completamente apagada, e a Dawnbreaker ficou à deriva na imensidão do espaço, perdida por milênios até atingir um planeta desconhecido.\n\nLá, ela descansou, adormecida; até que a presença de uma jovem estrela andarilha acendeu uma forja de energia ancestral — uma relíquia dos Filhos que, como ela, ficou enterrada por incontáveis eras, sob detritos avermelhados. Agora, com uma pequena porção dos seus antigos poderes restaurada pela forja, Valora levantou em uma terra assolada pela guerra e as incansáveis forças do caos. Ela sabe que os seus deuses podem ter ido embora, mas o peso do seu martelo continua lá — tão pesado quanto o seu desejo de erguê-lo com justiça, em nome da bondade e da luz.',
      shortDescription:
        'A Dawnbreaker brilha no coração da batalha, alegre em esmagar inimigos com o seu martelo celestial e curar aliados próximos. Ela se diverte arremessando o martelo por entre múltiplos inimigos e criando um rastro flamejante no seu retorno, esperando a hora certa para usar o seu verdadeiro poder cósmico para voar em ajuda aos seus companheiros de equipe — pronta para derrotar inimigos no campo de batalha, não importa onde estejam.',
    },
    dazzle: {
      title: 'POWERFUL HEALER WHO CAN BRIEFLY PREVENT DEATH',
      history:
        'Each young acolyte to the Dezun order must complete a series of rites before becoming a shadow priest. The final rite, the rite of shades, is a harrowing spiritual journey through the Nothl Realm, an unpredictable domain from which not all visitants return. Of those who do, some return mad. Others return with strange aptitudes. But all who go there are changed by their experiences.\n\nDriven by the need for enlightenment, Dazzle was the youngest of his tribe ever to request the sacred ritual. At first the order refused him, saying he was too young. But Dazzle was not to be dissuaded. Sensing something special in the headstrong young acolyte, the elders relented. Dazzle drank down the sacred potion and sat by the fire while the rest of his tribe danced through the night.\n\nIn this ethereal dimension of the Nothl Realm, the properties of light and dark are inverted. Thus his brilliant healing light, beautiful to our eye, is actually a sinister kind of evil; and the darkest deeds are done in a dazzling glow. The elders intuition was prophetic: Dazzle returned to his people as a Shadow Priest like none seen before, with the power to heal as well as to destroy. Now he uses his gift to cut down his enemies and mend his friends',
      shortDescription:
        'Nascido para apoiar os seus companheiros em batalha, Dazzle mantém os seus aliados feridos vivos para que depois possam trazer a morte aos inimigos. A sua mágica estranha pode se entrelaçar entre qualquer armadura próxima, enfraquecendo os seus inimigos e fortalecendo os seus aliados.',
    },
    death_prophet: {
      title: 'SUMMONS AN ARMY OF GHOSTS TO ATTACK',
      history:
        'Krobelus was a Death Prophet--which is one way of saying she told fortunes for the wealthiest of those who wished to look beyond the veil. But after years of inquiring on behalf of others, she began to seek clues on her own fate. When death refused to yield its secrets, she tried to buy them with her life. But the ultimate price proved insufficient.\n\nDeath disgorged her again and again, always holding back its deepest mysteries. Her jealousy grew. Others could die for eternity--why not she? Why must she alone be cast back on the shores of life with such tiresome regularity? Why was she not worthy of the one thing all other living creatures took for granted? Still, she would not be discouraged.\n\nEach time she returned from the grave, she brought a bit of death back with her. Wraiths followed her like fragments of her shattered soul; her blood grew thin and ectoplasmic; the feasting creatures of twilight took her for their kin.. She gave a little of her life with every demise, and it began to seem as if her end was in sight. With her dedication to death redoubled, and no client other than herself, Krobelus threw herself ever more fervently into deaths abyss, intent on fulfilling the one prophecy that eluded her: That someday the Death Prophet would return from death no more.',
      shortDescription:
        'Quando ela liberta o seu exército de fantasmas, a Death Prophet é excelente em demolir não só os seus inimigos, mas também as suas estruturas. Liderando as forças da sua equipe em direção à base inimiga com ondas e mais ondas do seu enxame danoso, o seu massacre pode parecer implacável.',
    },
    disruptor: {
      title: 'TRAPS AND SILENCES FOES IN HIS STATIC STORM',
      history:
        'High on the wind-ravaged steppes of Druud, a gifted young stormcrafter called Disruptor was the first to unlock the secrets of the summer squalls. Constantly under assault from both seasonal storms and encroachment from civilized kingdoms to the South, the upland Oglodi have for centuries struggled to subsist atop the endless tablelands. They are the fractured remnant of a once-great civilization, a fallen tribe, their stormcraft strange and inscrutable, cobbled together from scraps of lost knowledge which even they no longer fully understand. For those on the high plain, weather has become a kind of religion, worshiped as both the giver and taker of life. But the electrical storms that bring life-sustaining rains arrive at a cost, and many are the charred and smoking corpses left in their wake.\n\nAlthough small for his kind, Disruptor is fearless, and driven by an insatiable curiosity. As a youth, while still unblooded and without a stryder, he explored the ruins of the ancestral cities, searching through collapsed and long-moldering libraries, rummaging through rusting manufactories. He took what he needed and returned to his tribe. Adapting a coil of ancient design, he harnessed the power of electrical differential and now calls down the thunder whenever he wishes. Part magic, part craftsmanship, his coils hold in their glowing plates the power of life and death--a power wielded with precision against the landed castes to the South, and any interlopers who cross into ancient Oglodi lands.',
      shortDescription:
        'Estragar os planos dos seus inimigos é a especialidade do Disruptor. Invocando barreiras intransitáveis, ele aprisiona os seus alvos na sua tempestade silenciadora e, se algum deles tentar algo inesperado, ele pode simplesmente teletransportá-lo de volta para onde estava anteriormente.',
    },
    doom: {
      title: 'PODE IMPEDIR QUE UM INIMIGO USE HABILIDADES E ITENS',
      history:
        'He that burns and is not consumed, devours and is never sated, kills and is beyond all judgment--Lucifer brings doom to all who would stand against him. Bearing away souls on the tip of a fiery sword, he is the Fallen One, a once-favored general from the realm behind the light, cast out for the sin of defiance: he would not kneel.\n\nSix times his name was tolled from the great bell of Vashundol. Six and sixty times his wings were branded, until only smoking stumps remained. Without wings, he slipped loose from the tethers that bound him within the light and he fell screaming to earth. A crater in the desert, Paradise lost. Now he attacks without mercy, without motive, the only living being able to move freely between the seven dark dominions. Lashed by inescapable needs, twisted by unimaginable talents, Doom carries his own hell with him wherever he goes. Defiant to the last. Eventually, the world will belong to Doom.',
      shortDescription:
        'De uma forma ou de outra, o Doom incapacita os seus inimigos. Devorando criaturas para absorver as habilidades que tinham em vida, ele pode condenar as magias e itens de um dos seus adversários a um silêncio prolongado, enquanto queima os que se opõem a ele.',
    },
    dragon_knight: {
      title:
        'TRANSFORMA-SE EM UM FORMIDÁVEL DRAGÃO COM ATAQUES DE LONGO ALCANCE',
      history:
        'After years on the trail of a legendary Eldwurm, the Knight Davion found himself facing a disappointing foe: the dreaded Slyrak had grown ancient and frail, its wings tattered, its few remaining scales stricken with scale-rot, its fangs ground to nubs, and its fire-gouts no more threatening than a pack of wet matchsticks.\n\nSeeing no honor to be gained in dragon-murder, Knight Davion prepared to turn away and leave his old foe to die in peace. But a voice crept into his thoughts, and Slyrak gave a whispered plea that Davion might honor him with death in combat. Davion agreed, and found himself rewarded beyond expectation for his act of mercy: As he sank his blade in Slyraks breast, the dragon pierced Davion throat with a talon. As their blood mingled, Slyrak sent his power out along the Blood Route, sending all its strength and centuries of wisdom to the knight. The dragons death sealed their bond and Dragon Knight was born. The ancient power slumbers in the Dragon Knight Davion, waking when he calls it. Or perhaps it is the Dragon that calls the Knight...',
      shortDescription:
        'Quando ele toma a sua assustadora forma de dragão, o Dragon Knight aterroriza qualquer um que o encarar. Forte e adaptável, ele pode atordoar os seus inimigos e queimar todos à sua frente, muitas vezes dando aos seus aliados a situação que precisam para levá-los à vitória.',
    },
    earth_spirit: {
      title: 'DESATIVA E REPOSICIONA OS SEUS INIMIGOS',
      history:
        'Deep amid the Upland crags and cliffs there runs a seam of sacred jade long foresworn by highland miners. From this rare material, the likeness of the great general Kaolin was carved and buried at the head of a stone funerary army ten thousand strong--a force of soldiers and holy men, jesters and acrobats, carved by crafstmen and entombed for millennia in the dark embrace of the Earth.\n\nWhat the craftsmen had not known was that within the strange seam of jade flowed the spirit of the Earth itself--an elemental force at one with the planet. When the force within the carved jade found itself cut off from the lifes blood of the world, it gathered its strength over the course of a thousand years and dug itself free and into the light. Now the great Kaolin Earth Spirit strides the Upland roads, fighting for the spirit of the Earth; and in times of need calls forth remnants of his buried army still locked in the loving embrace of the soil.',
      shortDescription:
        'O Earth Spirit mantém os inimigos no caos e os aliados na luta. Adaptando-se a qualquer situação na batalha, ele pode mandar os seus resquícios de estátua de um lado para o outro para causar dano a inimigos ou tirar um aliado das garras da morte.',
    },
    earthshaker: {
      title: 'INTERROMPE INIMIGOS COM ATORDOAMENTOS REGULARES',
      history:
        'Like a golem or gargoyle, Earthshaker was one with the earth but now walks freely upon it. Unlike those other entities, he created himself through an act of will, and serves no other master. In restless slumbers, encased in a deep seam of stone, he became aware of the life drifting freely above him. He grew curious.\n\nDuring a season of tremors, the peaks of Nishai shook themselves loose of avalanches, shifting the course of rivers and turning shallow valleys into bottomless chasms. When the land finally ceased quaking, Earthshaker stepped from the settling dust, tossing aside massive boulders as if throwing off a light blanket.\n\nHe had shaped himself in the image of a mortal beast, and named himself Raigor Stonehoof. He bleeds now, and breathes, and therefore he can die. But his spirit is still that of the earth; he carries its power in the magical totem that never leaves him. And on the day he returns to dust, the earth will greet him as a prodigal son.',
      shortDescription:
        'Seja bloqueando a rota de fuga de um inimigo, dividindo as suas forças ou rompendo a terra sob os pés dos seus inimigos, o Earthshaker se beneficia de ataques sem aviso. Quem sobreviver aos tremores secundários dos seus ataques ainda terá que enfrentar o seu poderoso totem.',
    },
    elder_titan: {
      title: 'CAUSA DANO E INCAPACITA INIMIGOS COM O SEU ESPÍRITO ASTRAL',
      history:
        'Well may you ask, "How did this world take its form?" Why of all the worlds in creation, has this one its strange properties, its diverse and motley collection of creatures, cultures and lore? "The answer," One whispers, "lies with the Titans."\n\nThese original progenitors were there near the Beginning--if not actual witnesses to the creation, then born with it still echoing in their ears. Stamped with the earliest energies of the universe, they wished nothing more than to continue as creators themselves. Thus they bent to the task of shaping matter to their will: hammering and heating, bending and blasting. And when matter proved less challenging than they liked, they turned their tools upon themselves, reshaping their minds and reforging their spirits until they had become beings of great endurance. Reality itself became the ultimate object of their smithing. Yet, along the way, they sometimes erred. In cases of great ambition, mistakes are unavoidable.\n\nThe one we know as the Elder Titan was a great innovator, one who studied at the forge of creation. In honing his skills, he shattered something that could never be repaired, only thrown aside. He fell into his own broken world, a shattered soul himself. There he dwelt among the jagged shards and fissured planes, along with other lost fragments that had sifted down through the cracks in the early universe. And this is why the world we know resembles an isle of castaways, survivors of a wreck now long forgotten. Forgotten, that is, by all but the One who blames himself. He spends his time forever seeking a way to accomplish the repairs, that he might rejoin the parts of his broken soul, that we and the world alike might all be mended. This is the One we know as Elder Titan.',
      shortDescription:
        'Liderando o caminho com o seu espirito astral, o Elder Titan pode atacar de qualquer direção. Imobilizando inimigos com um pisão dos seus cascos enquanto que a sua presença corrói as suas defesas, ele divide a própria terra para eliminar os seus inimigos.',
    },
    ember_spirit: {
      title: 'RAPIDAMENTE ATACA E ACORRENTA OS SEUS INIMIGOS',
      history:
        'Perdida nos confins das Montanhas da Lamentação, a Fortaleza Flamejante permanece abandonada. As salas de treinamento, vazias. O pátio, coberto de folhas e poeira. Dentro do seu selado templo, há um estrado. Sobre esse estrado, há um caldeirão de topázio repleto de cinzas ancestrais, resquícios de uma pira funerária do poeta-guerreiro Xin. Por três gerações, Xin ensinou aos seus acólitos os Vínculos da Flama Guardiã, uma série de meditações que treinam a mente e corpo para a dura realidade que ocorre além dos muros da fortaleza.\n\nNo entanto, ao ensinar o caminho a um guerreiro, ele obteve a rivalidade do próprio e quando se tornou maduro o suficiente, Xin fora superado e morto. Os seus seguidores se espalharam pelo vento. À medida que os anos se tornaram séculos e os seguidores, descendentes, os seus ensinamentos continuaram a existir através de sutis sussurros e ações. Tocado pelo legado milenar do professor, o Celestial Ardente, curioso aspecto do fogo, enviou-se à Fortaleza Flamejante para reacender as cinzas da pira. Destas brasas brilhantes emergiu uma imagem de Xin, embalsamado em fogo, o seu semblante pensativo preparado para treinar e ensinar, para espalhar as chamas do saber por todos que buscam orientação.',
      shortDescription:
        'Ágil e elusivo, o Ember Spirit ataca todos os inimigos próximos em uma rápida sucessão e amarra-os com correntes ardentes. Correndo velozmente pelo campo de batalha para chegar a um dos seus resquícios explosivos, poucos podem evitar ou capturar a sua chama.',
    },
  }[heroPath]);
